# Generated by Django 5.1.3 on 2024-12-04 09:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_user_usertype'),
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stransmission', models.CharField(choices=[('Manual', 'Manual'), ('Auto', 'Auto')], max_length=30)),
                ('sfuel', models.CharField(choices=[('Petrol', 'Petrol'), ('Diesel', 'Diesel'), ('C.N.G', 'C.N.G')], max_length=30)),
                ('cname', models.CharField(max_length=30)),
                ('cyear', models.IntegerField()),
                ('cprice', models.IntegerField()),
                ('desc', models.TextField()),
                ('cimage', models.ImageField(default='', upload_to='cimage/')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.user')),
            ],
        ),
    ]
