# Generated by Django 5.1.3 on 2024-12-04 10:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_car'),
    ]

    operations = [
        migrations.RenameField(
            model_name='car',
            old_name='cname',
            new_name='yname',
        ),
    ]
