# Generated by Django 5.1.4 on 2025-01-03 11:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='Username',
            new_name='fullname',
        ),
    ]
